---
- hosts: localhost
  tasks:
  - name: Include yaml variables
    include_vars: ../inputs.yml

  - name: Install with pip
    pip:
      name:
        - requests
        - docker

  - name: Configure function handler
    template:
      src: "python-function-template/handler.py"
      dest: "image-resize-template/function/handler.py"
    ignore_errors: yes

  - name: Configure function handler
    template:
      src: "python-function-template/minio_handler.py"
      dest: "image-resize-template/function/minio_handler.py"
    ignore_errors: yes

  - name: Remove built function image
    become: True
    shell: "docker image rm {{ resize_image_name }}"
    ignore_errors: yes

  - name: Build function image from Dockerfile
    become: True
    shell: "docker image build image-resize-template -t {{ resize_image_name }} "

  - name: Archive image
    become: True
    shell: "docker save -o {{ resize_image_name }}.tar {{ resize_image_name }}"
...
