---
- hosts: localhost
  tasks:
  - name: Include yaml variables
    include_vars: ../inputs.yml

  - name: Install docker
    shell: "{{ item }}"
    with_items:
      - curl -fsSL https://get.docker.com | sh -
      - sudo usermod -aG docker pi

  - name: Install with pip
    pip:
      name:
        - requests
        - docker

  - name: Uprade packages
    shell: "{{ item }}"
    with_items:
      - wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
      - sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb
      - sudo rm libseccomp2_2.5.1-1_armhf.deb

  - name: Set local registry
    shell: "{{ item }}"
    become: True
    with_items:
      - docker run -d -p 5000:5000 --restart=always --name registry registry:2
    ignore_errors: yes

  - name: Remove built function image
    become: True
    shell: "docker image rm {{ image_name }}"
    ignore_errors: yes

  - name: Build function image from Dockerfile
    become: True
    shell: "docker image build docker-template -t {{ image_name }}"

  - name: Push image
    become: True
    shell: "docker push {{ image_name }}"
...
