---
- hosts: localhost
  tasks:
  - name: Include yaml variables
    include_vars: ../inputs.yml

  - name: Install with pip
    pip:
      name:
        - requests
        - docker

  - name: Uprade packages
    shell: "{{ item }}"
    with_items:
      - wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
      - sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb

  - name: Set local registry
    shell: "{{ item }}"
    become: True
    with_items:
      - docker run -d -p 5000:5000 --restart=always --name registry registry:2
    ignore_errors: yes

  - name: Configure function handler
    template:
      src: "python-function-template/handler.py"
      dest: "image-resize-template/function/handler.py"
    ignore_errors: yes

  - name: Configure function handler
    template:
      src: "python-function-template/minio_handler.py"
      dest: "image-resize-template/function/minio_handler.py"
    ignore_errors: yes

  - name: Remove built function image
    become: True
    shell: "docker image rm {{ resize_image_name }}"
    ignore_errors: yes

  - name: Build function image from Dockerfile
    become: True
    shell: "docker image build image-resize-template -t {{ resize_image_name }} "

  - name: Push image
    become: True
    shell: "docker push {{ resize_image_name }}"
...
