---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Install prerequsiste python3 packages
    pip:
      name:
        - botocore==1.12.236
        - boto==2.49.0
        - boto3==1.9.236
      state: latest

  - name: Create MinIO "{{ bucket_in }}" bucket
    aws_s3:
      bucket: "{{ bucket_in }}"
      mode: create
      aws_access_key: "{{ minio_user }}"
      aws_secret_key: "{{ minio_pass }}"
      s3_url: "http://{{ hostname }}:9000"

  - name: Create MinIO "{{ bucket_out }}" bucket
    aws_s3:
      bucket: "{{ bucket_out }}"
      mode: create
      aws_access_key: "{{ minio_user }}"
      aws_secret_key: "{{ minio_pass }}"
      s3_url: "http://{{ hostname }}:9000"
...