---
- hosts: all
  tasks:
  - name: Install MinIO client
    shell: "{{ item }}"
    with_items:
      - wget https://dl.min.io/client/mc/release/linux-amd64/mc
      - chmod +x mc
      - mc alias set myminio http://{{ master_node_ip }}:9000 {{ minio_user }} {{ minio_password }}

  - name: Create MinIO "{{ bucket_in_name }}" bucket
    shell: "mc mb {{ bucket_in_name }}"

  - name: Create MinIO "{{ bucket_out_name }}" bucket
    shell: "mc mb {{ bucket_out_name }}"
...