---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Remove MinIO "{{ bucket_in }}" bucket
    aws_s3:
      bucket: "{{ bucket_in }}"
      mode: delete
      aws_access_key: "{{ minio_user }}"
      aws_secret_key: "{{ minio_pass }}"
      s3_url: "http://{{ minio_ip }}:9000"

  - name: Remove MinIO "{{ bucket_out }}" bucket
    aws_s3:
      bucket: "{{ bucket_out }}"
      mode: delete
      aws_access_key: "{{ minio_user }}"
      aws_secret_key: "{{ minio_pass }}"
      s3_url: "http://{{ minio_ip }}:9000"