---
- hosts: localhost
  gather_facts: no
  tasks:
  - name: Remove MinIO "{{ bucket_in_name }}" bucket
    shell: "mc rb {{ bucket_in_name }}"

  - name: Remove MinIO "{{ bucket_out_name }}" bucket
    shell: "mc rb {{ bucket_out_name }}"