---
- hosts: localhost
  remote_user: pi
  gather_facts: no
  tasks:
  - name: Kill all bucket notification processes
    shell: "kill $(ps -ef | grep 'bucket-notification.py' | awk '{print $2}')"
    ignore_errors: yes
...