---
- hosts: k3s_rpi_master
  remote_user: pi
  become: True
  gather_facts: True

  tasks:
    - name: Create passwordless ssh
      command: "{{ item }}"
      with_items:
        - ssh-keygen
        - ssh-copy-id pi@localhost

    - name: Install arkade
      command: "{{ item }}"
      with_items:
        - curl -sSL https://dl.get-arkade.dev | sudo sh
        - arkade get kubectl
        - sudo mv /home/pi/.arkade/bin/kubectl /usr/local/bin/
        - arkade get k3sup
        - sudo mv /home/pi/.arkade/bin/k3sup /usr/local/bin/

    - name: Install k3s
      command: "{{ item }}"
      with_items:
        - export IP="0.0.0.0"
        - arkade get kubectl
        - sudo mv /home/pi/.arkade/bin/kubectl /usr/local/bin/
        - arkade get k3sup
        - sudo mv /home/pi/.arkade/bin/k3sup /usr/local/bin/
        - arkade install kubernetes-dashboard

    - name: Get token from master
      shell: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_node_token

- hosts: k3s_rpi_worker
  remote_user: pi
  become: True
  gather_facts: True

  tasks:
    - set_fact:
        k3s_master_host: "{{ groups['k3s_rpi_master'][0] }}"

    - set_fact:
        k3s_master_token: "{{ hostvars[k3s_master_host]['k3s_node_token'].stdout }}"

    - name: Install / upgrade k3s on worker nodes and connect to master
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_node_ip }}:6443 K3S_TOKEN={{ k3s_master_token }} sh -"

- hosts: k3s_rpi_master
  remote_user: pi
  become: True
  gather_facts: True

  tasks:
    - name: Install OpenFAAS
      command: "{{ item }}"
      with_items:
        - arkade get faas-cli
        - arkade install openfaas
        - curl -SLsf https://cli.openfaas.com | sudo sh
        - kubectl rollout status -n openfaas deploy/gateway
        - kubectl port-forward -n openfaas svc/gateway 8080:8080 &

    - name: Login FAAS CLI
      command: "{{ item }}"
      with_items:
        - PASSWORD=$(kubectl get secret -n openfaas basic-auth -o jsonpath="{.data.basic-auth-password}" | base64 --decode; echo)
        - echo -n $PASSWORD | faas-cli login --username admin --password-stdin

    - name: Print password for OpenFAAS Page
      command: echo $PASSWORD
      register: pass

    - debug: msg="{{ pass.stdout }}"

    - name: Deploy sample function
      shell: "faas-cli store deploy figlet"
