---
- hosts: k3s_rpi_master
  remote_user: pi
  gather_facts: True

  tasks:
    - name: Include deployment variables
      include_vars: ../inputs.yml

    - name: Install arkade and get packages
      shell: "{{ item }}"
      with_items:
        - curl -sSL https://dl.get-arkade.dev | sudo sh
        - arkade get kubectl
        - arkade get k3sup

    - name: Install kubectl and k3s
      shell: "{{ item }}"
      become: True
      with_items:
        - mv /home/pi/.arkade/bin/k3sup /usr/local/bin/
        - mv /home/pi/.arkade/bin/kubectl /usr/local/bin/

    - name: Install k3s
      shell: "{{ item }}"
      with_items:
        - export IP="{{ master_node_ip }}"
        - k3sup install --ip "{{ master_node_ip }}" --user pi
        - export KUBECONFIG=/home/pi/radonpi/kubeconfig
        - kubectl config set-context default
        - kubectl config view --raw >~/.kube/config
        - kubectl create secret docker-registry secret --docker-username=admin --docker-password=XXXX
        - arkade install kubernetes-dashboard

    - name: Get token from master
      become: True
      shell: "cat /var/lib/rancher/k3s/server/node-token"
      register: k3s_node_token

- hosts: k3s_rpi_worker
  remote_user: pi
  become: True
  gather_facts: True

  tasks:
    - set_fact:
        k3s_master_host: "{{ groups['k3s_rpi_master'][0] }}"

    - set_fact:
        k3s_master_token: "{{ hostvars[k3s_master_host]['k3s_node_token'].stdout }}"

    - name: Install / upgrade k3s on worker nodes and connect to master
      shell: "curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_node_ip }}:6443 K3S_TOKEN={{ k3s_master_token }} sh -"

- hosts: k3s_rpi_master
  remote_user: pi

  tasks:
    - name: Install OpenFAAS
      shell: "arkade install openfaas --kubeconfig /home/pi/radonpi/kubeconfig"

    - name: Install faas-cli
      shell: "{{ item }}"
      with_items:
        - arkade get faas-cli
        - curl -SLsf https://cli.openfaas.com | sudo sh
        - kubectl port-forward -n openfaas svc/gateway 8080:8080 &
        - kubectl get secret -n openfaas basic-auth -o jsonpath='{.data.basic-auth-password}' --kubeconfig /home/pi/radonpi/kubeconfig | base64 --decode > ~/faas_pass.txt

    - name: Login FAAS CLI
      shell: "kubectl get secret -n openfaas basic-auth -o jsonpath='{.data.basic-auth-password}' --kubeconfig /home/pi/radonpi/kubeconfig | base64 --decode | faas-cli login --username admin --password-stdin"

    - name: Deploy sample function
      shell: "faas-cli store deploy figlet"

    - name: Install and run MinIO server
      shell: "{{ item }}"
      with_items:
        - wget https://dl.minio.io/server/minio/release/linux-arm/minio
        - wget https://dl.minio.io/client/mc/release/linux-arm/mc
        - chmod +x mc
        - chmod +x minio
        - sudo ln -s /home/pi/radonpi/minio /usr/bin/minio
        - sudo ln -s /home/pi/radonpi/mc /usr/bin/mc
        - MINIO_ROOT_USER={{ minio_user }} MINIO_ROOT_PASSWORD={{ minio_password }} ./minio server ~ &
        - mc alias set myminio http://{{ master_node_ip }}:9000 {{ minio_user }} {{ minio_password }}
